CREATE TABLE DEPT (
DNUM INT(5) AUTO_INCREMENT PRIMARY KEY,
NAME VARCHAR(20) NOT NULL,
AREA CHAR(1) CHECK (AREA IN ('N', 'S')),
MGR INT(5) UNIQUE
);

CREATE TABLE EMP (
ENUM INT(6) AUTO_INCREMENT PRIMARY KEY,
NAME VARCHAR(15) NOT NULL,
SAL DECIMAL(11,2) NOT NULL,
TAX DECIMAL(10,2),
DNUM INT(5) NOT NULL,
MGR INT(5),
FOREIGN KEY (DNUM) REFERENCES DEPT(DNUM)
);

CREATE TABLE SUPPLIER (
SNUM INT(5) AUTO_INCREMENT PRIMARY KEY,
NAME VARCHAR(25) UNIQUE,
CITY VARCHAR(3) CHECK (CITY IN ('NGP', 'DLH', 'UMR'))
);

CREATE TABLE SUPPLY (
PNUM VARCHAR(4),
SNUM INT(5),
DNUM INT(5),
QTY INT(6),
PRIMARY KEY (PNUM, SNUM, DNUM),
FOREIGN KEY (SNUM) REFERENCES SUPPLIER(SNUM),
FOREIGN KEY (DNUM) REFERENCES DEPT(DNUM)
);

INSERT INTO DEPT (NAME, AREA) VALUES ('Personnel', 'N'), ('Inventory
& Purchase', 'S');

INSERT INTO EMP (NAME, SAL, DNUM, MGR) VALUES

('John', 90000.00, 1, NULL),
('Jane', 85000.00, 2, 101),
('Bob', 80000.00, 1, NULL),
('Alice', 95000.00, 1, 102),
('Charlie', 88000.00, 2, 102),
('Jyotika', 890270.00, 1, 23);

INSERT INTO SUPPLIER (NAME, CITY) VALUES ('Supplier1', 'NGP'),
('Supplier2', 'DLH'), ('Supplier3', 'UMR');

INSERT INTO SUPPLY (PNUM, SNUM, DNUM, QTY) VALUES
('PD1', 1, 1, 100),
('PD2', 2, 2, 50),
('PD3', 3, 1, 75),
('PD4', 1, 2, 60),
('PD5', 2, 1, 120),
('PD33', 1, 2, 30);

SELECT NAME, SAL
FROM EMP
WHERE DNUM = 2;

SELECT S.NAME AS SupplierName, S.DNUM AS DepartmentNumber, D.NAME AS
DepartmentName
FROM SUPPLY AS SP
JOIN SUPPLIER AS S ON SP.SNUM = S.SNUM
JOIN DEPT AS D ON SP.DNUM = D.DNUM
WHERE D.NAME = 'Personnel';

SELECT S.NAME AS SupplierName
FROM SUPPLIER AS S
JOIN SUPPLY AS SP ON S.SNUM = SP.SNUM
JOIN DEPT AS D ON SP.DNUM = D.DNUM
WHERE S.CITY = 'UMR' AND D.AREA = 'N';

SELECT NAME, D.NAME AS Department, D.AREA
FROM EMP
JOIN DEPT AS D ON EMP.DNUM = D.DNUM
WHERE NAME LIKE 'A%';


SELECT S.NAME AS SupplierName, QTY, D.NAME AS DepartmentName FROM SUPPLY AS SP 
JOIN SUPPLIER AS S ON SP.SNUM = S.SNUM 
JOIN DEPT AS D ON SP.DNUM = D.DNUM 
WHERE SP.PNUM = 'PD33'; 

CREATE TABLE EMP_ADMN AS SELECT ENUM, NAME, MGR, DNUM FROM EMP; CREATE TABLE EMP_PAY AS SELECT ENUM, NAME, SAL, TAX FROM EMP; 

SELECT ENUM, NAME, SAL AS GRS_PAY, (SAL - TAX) AS NET_PAY FROM EMP;

INSERT INTO EMP (ENUM, NAME, SAL, TAX, DNUM, MGR) 
VALUES (9218, 'Jyotika', 890270.00, 89000.00, 988, 23); 

SELECT * 
FROM EMP 
WHERE SAL > 800000.00 AND DNUM IN (SELECT DNUM FROM DEPT WHERE AREA  = 'S'); 

SELECT D.NAME AS DepartmentName, S.NAME AS SupplierName FROM SUPPLY AS SP 
JOIN DEPT AS D ON SP.DNUM = D.DNUM 
JOIN SUPPLIER AS S ON SP.SNUM = S.SNUM 
WHERE SP.PNUM = 'PD33';


 











